set superuser command if not root

diff --git a/vm-scripts/cache-save b/vm-scripts/cache-save
--- a/vm-scripts/cache-save
+++ b/vm-scripts/cache-save
@@ -1,15 +1,21 @@
 #!/usr/bin/bash
 
+SUPERUSER_COMMAND="sudo"
+
+if [[ $EUID -e 0 ]]; then
+    SUPERUSER_COMMAND=""
+fi
+
 print_usage() {
-        echo "Usage: $0 <source_directory> <cache-key>"
-        echo "Example: $0 /path/to/source_dir source_dir-cache-key"
-        exit 1
+    echo "Usage: $0 <source_directory> <cache-key>"
+    echo "Example: $0 /path/to/source_dir source_dir-cache-key"
+    exit 1
 }
 
 echo "Cache Saver v0.1"
 
 if [ $# -lt 2 ]; then
-        print_usage
+    print_usage
 fi
 
 original_dir="$(pwd)"
@@ -20,8 +26,8 @@ dest_file="$(basename $dest_path)"
 
 
 if [ ! -d "$source_dir" ]; then
-        echo "Error: '$source_dir' is not a valid directory."
-        print_usage
+    echo "Error: '$source_dir' is not a valid directory."
+    print_usage
 fi
 
 parent_dir="$(dirname $source_dir)"
@@ -31,12 +37,10 @@ cd "$parent_dir" || { echo "Error: Cannot change to parent directory"; exit 1; }
 
 # if the destination exists, remove it as it's about to be replaced.
 if [ -f "$dest_path" ]; then
-        rm -rf "$dest_path"
+    rm -rf "$dest_path"
 fi
 
-sudo tar -zcf "$dest_file" --preserve-permissions "$base_dir" || { echo "Error: Failed to create cache archive."; exit 1; }
-sudo chown 1000:1000 "$dest_file"
-sudo -u "#1000" -g "#1000" cp "$dest_file" "$dest_path" || { echo "Error: Failed to move archive to cache location."; exit 1; }
-sudo rm "$dest_file"
+$SUPERUSER_COMMAND tar -zcf "$dest_file" --preserve-permissions "$base_dir" || { echo "Error: Failed to create cache archive."; exit 1; }
+$SUPERUSER_COMMAND mv "$dest_file" "$dest_path" || { echo "Error: Failed to move archive to cache location."; exit 1; }
 
 cd "$original_dir"
